
__columnMapper_Access__={
    ' Registro '                            :'REGISTRO'	,  
    ' Año '                                 :'ANO', 
    ' Mes '                                 :'MES', 
    ' Unidad '                              :'UNIDAD',
    ' Clase_produccion '                    :'CLASE PRODUCCIÓN'	, 
    ' Segmento_SICS '                       :'SEGMENTO SICS NS', 
    ' Oficina '                             :'OFICINA', 
    ' Cliente '                             :'CLIENTE', 
    ' Ramo '                                :'RAMO', 
    ' Comision_id'                          :'COMISION ID'	, 
    ' Comision_amortizacion '               :'COMISION AMORT',
    ' Comision_fact '                       :'COMISION FAC', 
    ' Comision_ingr '                       :'COMISIONES' , 
    ' Segmento_marsh '                      :'SEGMENTO MARSH',
    ' Subramo '                             :'SUBRAMO', 
    ' Practica_industria '                  :'PRACTICA IND', 
    ' Grupo Empresarial '                   :'GRUPO',
    'NOTA'                                  :'NOTA',
    'Fuente '                               :'FUENTE', 
    'TRIMESTRE'	                            :'TRIMESTRE',
    'REGIONES'                              :'REGIONES',	
    ' Gerente_comercial Póliza'             :'GERENTE',	
    'ARCHIVO'                               :'ARCHIVO',	
    'PRACTICA'                              :'PRACTICA',
    ' Canal '                               :'CANAL',
    'Re definicion'                         :'Re definicion',	
    'Specialty'                             :'Specialty'	,
    'Subspecialty'                          :'Sub-specialty',
}